### ISSUE TITLE
Breaks when ordering of inclusions is different

### ISSUE THREAD

**Issue by djay** [40ants/github-matrix#1]
e.g.

```
        python-version: ['2.7']
        plone-version: 
          - '4.1'
          - '4.3'
          - '5.0'
          - '5.1'
          - '5.2'
        include:
          - plone-version: 5.2
            python-version: 3.7
          - plone-version: 5.2
            python-version: 3.8
```
ends up looking like

<img width="449" alt="Screen Shot 2021-02-02 at 4 40 13 pm" src="https://user-images.githubusercontent.com/41700/106581415-6a10d880-6575-11eb-98cc-b96cadde8091.png">
