### ISSUE TITLE
how to filter github action matrices (matrix fails to render as well)

### ISSUE THREAD

**Issue by mgood7123** [40ants/github-matrix#3]
Badge NO FILTER

[![](http://github-actions.40ants.com/mgood7123/prebuilder/matrix.svg)](https://github.com/mgood7123/prebuilder/actions)

`[![](http://github-actions.40ants.com/mgood7123/prebuilder/matrix.svg)](https://github.com/mgood7123/prebuilder/actions)`

Badge FILTERED

[![](http://github-actions.40ants.com/mgood7123/prebuilder/matrix.svg?only=CMake.run-build.ubuntu-latest,CMake.run-build.macOS-latest,CMake.run-build.windows-latest)](https://github.com/mgood7123/prebuilder/actions)

`[![](http://github-actions.40ants.com/mgood7123/prebuilder/matrix.svg?only=CMake.run-build.ubuntu-latest,CMake.run-build.macOS-latest,CMake.run-build.windows-latest)](https://github.com/mgood7123/prebuilder/actions)`

why does this have `Waiting For A Run` even though the workflow has succeeded?

also why does the matrix fail to render?

cmake.yaml:

```yaml
name: CMake

on:
  push:
    branches: [ main ]

concurrency:
  group: build
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
        
        - os: ubuntu-latest
          extension: so

        - os: macOS-latest
          extension: dylib

        - os: windows-latest
          extension: dll

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    
# ommited
```
