### ISSUE TITLE
Strategy / matrix / include should be processed

### ISSUE THREAD

**Issue by tribbloid** [40ants/github-matrix#5]
The following 2 strategy matrix are identical:

```
      matrix:
        scalaVersion: ["2.13.6", "2.13.7"]
```

equals

```
      matrix:
        include:
          - scalaVersion: "2.13.6"
          - scalaVersion: "2.13.7"
```

But only the first one can be parse successfully and generate the proper badge

The second produces multiple jobs in github actions, but as a badge they cannot be identified:

![badge-errors](https://user-images.githubusercontent.com/3441413/142078653-3168c698-a58f-475e-bb17-a70bcf8ec209.png)

Is this a known limitation?

**Comment by svetlyak40wt** [comment]
The case with "include" is not supported just because I didn't have it in mind :(

**Comment by svetlyak40wt** [comment]
Are there any cases when you really want to use second variant with `include` list instead of the first version?

**Comment by tribbloid** [comment]
Thanks a lot! In my case I sometimes want to construct an incomplete matrix, e.g.:

```
      matrix:
        include:
          - scalaVersion: "2.13.6"
            experimental: true
          - scalaVersion: "2.13.7"
            experimental: true
```

The argument ${{experimental}} can then affect some workflow behaviour
